import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { seedDailyDemo } from "./daily-demo.mjs";
import { Store } from "../dist/core/store.js";
import { atomic } from "../dist/core/files.js";
import { draftSkill, controlSkill } from "../dist/core/skill-library.js";
import { saveRecord } from "../dist/core/workspace.js";
import { listTasks, createProposal } from "../dist/core/tasks.js";
import {
  createConversation,
  appendConversation,
  submitChat,
} from "../dist/core/chat.js";
export async function seedExecutiveDemo(workspace) {
  const demo = await seedDailyDemo(workspace);
  const s = new Store(demo.workspace);
  try {
    const file = s.path(".hoi/workspace.json");
    atomic(
      file,
      JSON.stringify(
        { ...JSON.parse(readFileSync(file, "utf8")), environment: "demo" },
        null,
        2,
      ),
    );
    const date = (days) =>
      new Date(Date.parse(demo.date + "T12:00:00Z") + days * 86400000)
        .toISOString()
        .slice(0, 10);
    const save = (kind, record) =>
      saveRecord(s, { kind, expectedVersion: 0, record }, "local");
    const client = save("client", {
      name: "Lumen Learning (fictional)",
      owner: "Morgan (fictional)",
      notes: "Fictional UX demonstration only.",
    });
    const project = save("project", {
      name: "Lumen leadership workshop (fictional)",
      clientIds: [client.id],
      owner: "Alex (fictional)",
      status: "blocked",
      priority: "high",
      deliveryTypes: ["training", "consulting"],
      dueDate: date(-1),
      objective: "Confirm a fictional workshop outline",
      risks: "Waiting for fictional scope confirmation",
    });
    save("project", {
      name: "Lumen upcoming training (fictional)",
      deliveryTypes: ["training"],
      clientIds: [client.id],
    });
    save("training", {
      name: "Leadership workshop (fictional)",
      projectId: project.id,
      clientIds: [client.id],
      owner: "Alex (fictional)",
      start: date(3) + "T09:00:00Z",
      end: date(3) + "T12:00:00Z",
      timezone: "Europe/Paris",
    });
    const task = listTasks(s, "local")[0];
    createProposal(
      s,
      {
        key: "fictional-executive-review",
        task: {
          projectId: task.projectId,
          title: "Review the Cedar preparation plan (fictional)",
          outcome: "Human review of the existing fictional commitment",
          owner: null,
          dueDate: null,
        },
        evidence: task.evidence,
      },
      "local",
    );
    const skill = draftSkill(
      s,
      {
        name: "demo-consulting-review",
        expectedVersion: 0,
        markdown:
          "---\nname: demo-consulting-review\ndescription: Fictional consulting review example\nengineApiVersion: 1\nrequiredOperations: []\n---\nUse supplied evidence to list open questions. Never invent commitments or deadlines.",
      },
      "local",
    );
    controlSkill(
      s,
      {
        name: skill.id,
        expectedVersion: skill.version,
        action: "activate",
        revisionId: skill.revisions[0].revisionId,
        checksum: skill.revisions[0].checksum,
      },
      "local",
    );
    let conversation = createConversation(
      s,
      {
        title: "Cedar preparation — fictional example",
        host: "codex",
        projectId: task.projectId,
      },
      "local",
    );
    conversation = appendConversation(
      s,
      {
        id: conversation.id,
        expectedVersion: conversation.version,
        message: "What do we know about Cedar preparation?",
      },
      "local",
    );
    const run = conversation.turns[0];
    submitChat(
      s,
      run.id,
      run.version,
      {
        type: "answer",
        text: "# Fictional demonstration\n\nThis example response was seeded for UI review, not generated by a connected assistant. The recorded Cedar task evidence is available in the Evidence panel.\n\nConfirm outstanding work with the owner before treating it as a new commitment.",
        citations: task.evidence,
      },
      "local",
    );
    return {
      ...demo,
      environment: "demo",
      note: "Fictional client, project, tasks and training. No connected accounts or real company data.",
    };
  } finally {
    s.close();
  }
}
if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
)
  console.log(JSON.stringify(await seedExecutiveDemo(process.argv[2])));
